import { Check, X } from 'lucide-react';
import { LanDownload } from '../../types/api';
import { EmptyState, focusRing, formatBytes, formatTime, StatusBadge } from './LanUi';

type Props = { downloads: LanDownload[]; isPending: (key: string) => boolean; onDecision: (download: LanDownload, approved: boolean) => void };

function Actions({ item, isPending, onDecision }: Props & { item: LanDownload }) {
  if (!['preview_ready', 'requested'].includes(item.status || '')) return <span className="text-xs text-slate-500">Đã xử lý</span>;
  const busy = isPending(`download:${item.request_id}`);
  const base = `rounded-md px-2.5 py-1.5 text-xs font-medium disabled:cursor-not-allowed disabled:opacity-50 ${focusRing}`;
  return <div className="flex flex-wrap gap-2"><button disabled={busy} onClick={() => onDecision(item, true)} className={`${base} bg-emerald-700 hover:bg-emerald-600`}><Check className="mr-1 inline h-3.5 w-3.5" />{busy ? 'Đang xử lý…' : 'Duyệt tải'}</button><button disabled={busy} onClick={() => onDecision(item, false)} className={`${base} bg-rose-800 hover:bg-rose-700`}><X className="mr-1 inline h-3.5 w-3.5" />Từ chối</button></div>;
}

export function DownloadsPanel(props: Props) {
  return <section aria-labelledby="lan-downloads-heading" className="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div className="border-b border-slate-800 p-4"><h2 id="lan-downloads-heading" className="font-semibold">Duyệt tải video</h2><p className="mt-0.5 text-xs text-slate-500">Xác minh nội dung preview trước khi worker tải file nguồn.</p></div>
    {!props.downloads.length ? <EmptyState title="Chưa có yêu cầu chờ duyệt">Khi worker gửi preview, yêu cầu sẽ xuất hiện tại đây để admin duyệt hoặc từ chối.</EmptyState> : <><div className="hidden overflow-x-auto md:block"><table className="w-full text-sm"><thead className="bg-slate-950/40 text-slate-400"><tr><th className="p-3 text-left">Video</th><th className="p-3 text-left">Worker</th><th className="p-3 text-left">Dung lượng / thời lượng</th><th className="p-3 text-left">Trạng thái</th><th className="p-3 text-left">Quyết định</th></tr></thead><tbody>{props.downloads.map(item => <tr key={item.request_id} className="border-t border-slate-800 align-top"><td className="p-3"><p>{item.title || 'Video chưa có tiêu đề'}</p><p className="max-w-xl truncate text-xs text-slate-500" title={item.source}>{item.source || 'Không rõ nguồn'}</p><p className="mt-1 text-xs text-slate-600">Yêu cầu {formatTime(item.created_at)}</p></td><td className="p-3">{item.worker_id || '—'}</td><td className="p-3">{formatBytes(item.size_bytes)}<p className="text-xs text-slate-500">{item.duration_seconds != null ? `${Math.round(item.duration_seconds)} giây` : 'Chưa rõ thời lượng'}</p></td><td className="p-3"><StatusBadge status={item.status} />{item.error && <p className="mt-1 text-xs text-rose-300">{item.error}</p>}</td><td className="p-3"><Actions {...props} item={item} /></td></tr>)}</tbody></table></div>
      <div className="grid gap-3 p-3 md:hidden">{props.downloads.map(item => <article key={item.request_id} className="rounded-lg border border-slate-800 bg-slate-950/50 p-4"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><h3 className="truncate font-medium">{item.title || 'Video chưa có tiêu đề'}</h3><p className="truncate text-xs text-slate-500">{item.source || 'Không rõ nguồn'}</p></div><StatusBadge status={item.status} /></div><dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-slate-500">Worker</dt><dd>{item.worker_id || '—'}</dd></div><div><dt className="text-xs text-slate-500">Dung lượng</dt><dd>{formatBytes(item.size_bytes)}</dd></div><div><dt className="text-xs text-slate-500">Thời lượng</dt><dd>{item.duration_seconds != null ? `${Math.round(item.duration_seconds)} giây` : '—'}</dd></div><div><dt className="text-xs text-slate-500">Tạo lúc</dt><dd>{formatTime(item.created_at)}</dd></div></dl><div className="mt-4"><Actions {...props} item={item} /></div></article>)}</div></>}
  </section>;
}
