import { LanDownload, LanJob, LanOverview, LanWorker, SubtitleCueV1 } from '../../types/api';

export const MOCK_COMPLETED_CUES: SubtitleCueV1[] = [
  {
    cue_id: 'cue-mock-1',
    start_pts: 1.2,
    end_pts: 4.5,
    source_text: '你到底是谁？为什么会出现在这里？',
    translated_text: 'Rốt cuộc ngươi là ai? Tại sao lại xuất hiện ở đây?',
    confidence: 0.98,
    revision: 1,
    status: 'auto',
  },
  {
    cue_id: 'cue-mock-2',
    start_pts: 5.0,
    end_pts: 8.2,
    source_text: '我只是一个路过的剑客，无意冒犯。',
    translated_text: 'Ta chỉ là một kiếm khách qua đường, không có ý mạo phạm.',
    confidence: 0.96,
    revision: 1,
    status: 'auto',
  },
  {
    cue_id: 'cue-mock-3',
    start_pts: 9.1,
    end_pts: 13.8,
    source_text: '江湖险恶，各安天命，请姑娘就此止步。',
    translated_text: 'Giang hồ hiểm ác, số mệnh do trời, xin cô nương hãy dừng bước tại đây.',
    confidence: 0.99,
    revision: 1,
    status: 'reviewed',
  },
  {
    cue_id: 'cue-mock-4',
    start_pts: 14.5,
    end_pts: 18.0,
    source_text: '若今日不分胜负，你我便休想离开这座古刹！',
    translated_text: 'Nếu hôm nay không phân thắng bại, ngươi và ta đừng mong rời khỏi cổ tự này!',
    confidence: 0.97,
    revision: 1,
    status: 'auto',
  },
];

export function getInitialMockOverview(): LanOverview {
  const now = Date.now();
  const workers: LanWorker[] = [
    {
      worker_id: 'worker-alpha-rtx4090',
      hostname: 'WORKER-NODE-01 · windows',
      ip_address: '192.168.1.101:8901',
      platform: 'windows',
      app_version: '2.5.2',
      gpu_name: 'NVIDIA GeForce RTX 4090 24GB',
      vram_mb: 24576,
      capabilities: {
        cuda: true,
        ocr: true,
        transcribe: true,
        dubbing: true,
        downloader: true,
      },
      status: 'online',
      is_online: true,
      last_seen: now - 2000,
      active_job_id: 'job-mock-ocr-4090',
      queue_depth: 1,
    },
    {
      worker_id: 'worker-beta-m2max',
      hostname: 'STUDIO-MAC-M2 · darwin',
      ip_address: '192.168.1.102:8902',
      platform: 'darwin',
      app_version: '2.5.2',
      gpu_name: 'Apple M2 Max (32GB Unified Memory)',
      vram_mb: 32768,
      capabilities: {
        metal: true,
        mps: true,
        translate: true,
        dubbing: true,
        downloader: true,
      },
      status: 'online',
      is_online: true,
      last_seen: now - 4000,
      active_job_id: 'job-mock-dub-beta',
      queue_depth: 0,
    },
    {
      worker_id: 'worker-gamma-cpu',
      hostname: 'INGEST-SERVER-CPU · linux',
      ip_address: '192.168.1.103:8903',
      platform: 'linux',
      app_version: '2.5.0',
      gpu_name: 'Intel Core i9-13900K (No Discrete GPU)',
      vram_mb: 0,
      capabilities: {
        downloader: true,
        ffmpeg_cpu: true,
      },
      status: 'online',
      is_online: true,
      last_seen: now - 6000,
      active_job_id: null,
      queue_depth: 0,
    },
    {
      worker_id: 'worker-delta-draining',
      hostname: 'LEGACY-BOX-3060 · windows',
      ip_address: '192.168.1.104:8904',
      platform: 'windows',
      app_version: '2.4.9',
      gpu_name: 'NVIDIA GeForce RTX 3060 12GB',
      vram_mb: 12288,
      capabilities: {
        cuda: true,
        ocr: true,
      },
      status: 'draining',
      is_online: true,
      last_seen: now - 12000,
      active_job_id: null,
      queue_depth: 0,
    },
  ];

  const jobs: LanJob[] = [
    {
      job_id: 'job-mock-ocr-4090',
      project_id: 'proj-drama-ep01',
      worker_id: 'worker-alpha-rtx4090',
      job_type: 'ocr',
      stage: 'ocr',
      current_stage: 'Quét phụ đề OCR CUDA (Batch size 16)',
      status: 'running',
      progress: 42,
      attempt: 1,
      max_attempts: 3,
      lease_id: 'lease-alpha-0911',
      lease_expires_at: now + 25000,
      created_at: now - 120000,
      updated_at: now - 3000,
      metrics: {
        fps: 54.2,
        frames_processed: 480,
        total_frames: 1140,
        vram_peak_mb: 6140,
      },
    },
    {
      job_id: 'job-mock-dub-beta',
      project_id: 'proj-drama-ep02',
      worker_id: 'worker-beta-m2max',
      job_type: 'dubbing',
      stage: 'dubbing',
      current_stage: 'Lồng tiếng giọng AI Neural (Việt Nam)',
      status: 'running',
      progress: 78,
      attempt: 1,
      max_attempts: 3,
      lease_id: 'lease-beta-0912',
      lease_expires_at: now + 18000,
      created_at: now - 180000,
      updated_at: now - 2000,
      metrics: {
        cues_dubbed: 39,
        total_cues: 50,
        tts_engine: 'edge-tts',
      },
    },
    {
      job_id: 'job-mock-completed',
      project_id: 'proj-drama-ep03',
      worker_id: 'worker-alpha-rtx4090',
      job_type: 'full_pipeline',
      stage: 'completed',
      current_stage: 'Hoàn tất toàn bộ pipeline OCR & Dịch',
      status: 'completed',
      progress: 100,
      attempt: 1,
      max_attempts: 3,
      created_at: now - 600000,
      updated_at: now - 30000,
      metrics: {
        total_time_seconds: 74.2,
        cues_detected: 28,
        accuracy_score: '98.5%',
        fps: 48.6,
      },
    },
    {
      job_id: 'job-mock-failed',
      project_id: 'proj-drama-ep04',
      worker_id: 'worker-delta-draining',
      job_type: 'ocr',
      stage: 'ocr',
      current_stage: 'Trích xuất khung hình độ phân giải 4K',
      status: 'failed',
      progress: 15,
      attempt: 2,
      max_attempts: 3,
      error: 'CUDA Out of Memory: Đã dùng 11.9 GB / 12.0 GB VRAM. Hãy giảm batch size hoặc bật half-precision fp16.',
      created_at: now - 900000,
      updated_at: now - 120000,
    },
    {
      job_id: 'job-mock-queued',
      project_id: 'proj-drama-ep05',
      worker_id: undefined,
      job_type: 'translation',
      stage: 'translation',
      current_stage: 'Chờ worker có slot trống tiếp nhận',
      status: 'queued',
      progress: 0,
      attempt: 0,
      max_attempts: 3,
      created_at: now - 30000,
      updated_at: now - 30000,
    },
  ];

  const downloads: LanDownload[] = [
    {
      request_id: 'req-mock-dl-01',
      worker_id: 'worker-gamma-cpu',
      source: 'https://v.douyin.com/drama-ep05/1080p.mp4',
      title: 'Tập 05 - Đại Chiến Tiên Giới (1080p Web-DL)',
      duration_seconds: 1820,
      size_bytes: 485000000,
      status: 'preview_ready',
      created_at: now - 45000,
    },
    {
      request_id: 'req-mock-dl-02',
      worker_id: 'worker-gamma-cpu',
      source: 'https://cdn.example.com/trailers/trailer_ep06.mp4',
      title: 'Trailer Phim Ngắn Tập 06',
      duration_seconds: 145,
      size_bytes: 52400000,
      status: 'requested',
      created_at: now - 15000,
    },
  ];

  return {
    workers,
    jobs,
    downloads,
    worker_count: workers.length,
    online_worker_count: workers.filter(w => w.is_online && w.status !== 'disabled').length,
    running_job_count: jobs.filter(j => j.status === 'running').length,
    queue_depth: workers.reduce((sum, w) => sum + (w.queue_depth || 0), 0) + jobs.filter(j => j.status === 'queued').length,
    failed_job_count: jobs.filter(j => j.status === 'failed').length,
    pending_download_count: downloads.filter(d => ['requested', 'preview_ready'].includes(d.status || '')).length,
    fetched_at: now,
  };
}
